name: dotnet package
 
on:
  push:
    branches: ["malya"] 

jobs:
  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
 
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      - name: Test
        run: dotnet test --no-build --verbosity d -p:CollectCoverage=true -p:CoverletOutput=./coverage/coverage.opencover.xml -p:CoverletOutputFormat=opencover
      - name: Codecov
        uses: codecov/codecov-action@v3
        with: 
          files: SpaceBattle.Lib.Test/coverage/coverage.opencover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          override_pr: ${{ github.event.number }}
          override_commit: ${{ github.event.pull_request.head.sha }}   
      - name: Create Test Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        with:
          label: Unit Test Coverage
          color: brightgreen
          path: SpaceBattle.Lib.Test/coverage/coverage.opencover.xml     
      - name: Print code coverage
        run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"